# Generated by Django 3.2.6 on 2021-08-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegoBD', '0002_rosco_pregunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posision_numerica', models.CharField(max_length=1, verbose_name='letra en rosco')),
                ('posision_actual', models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='posision numerica')),
                ('puntaje_actual', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='puntaje acumulado')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('puntaje_total', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='puntaje total')),
            ],
        ),
        migrations.AlterField(
            model_name='rosco_pregunta',
            name='letra_rosco',
            field=models.CharField(max_length=1, verbose_name='letra de rosco'),
        ),
    ]
