# Generated by Django 3.2.6 on 2021-08-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegoBD', '0003_auto_20210827_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posision',
            name='posision_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=27, verbose_name='posision numerica'),
        ),
    ]
