# Generated by Django 3.2.6 on 2021-08-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegoBD', '0004_alter_posision_posision_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nro_contestadas',
            field=models.IntegerField(default=0, verbose_name='respuestas correctas'),
            preserve_default=False,
        ),
    ]
