# Generated by Django 3.2.6 on 2021-08-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegoBD', '0005_usuario_nro_contestadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nro_contestadas',
            field=models.IntegerField(default=0, verbose_name='respuestas correctas'),
        ),
    ]
