# Generated by Django 3.2.6 on 2021-09-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegoBD', '0006_alter_usuario_nro_contestadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='posision',
            name='contestadas',
            field=models.IntegerField(default=0, verbose_name='respuestas correctas'),
        ),
    ]
